language: c
compiler:
- clang
- gcc
python:
- "3.7"
sudo: false
cache: ccache

script:
- echo $PATH
- ls -l /opt/pyenv/shims
- which python
- python --version
- which python3
- python3 --version
- which cmake
- rm `which python3.6` `which python3.7`
- python3 -c "import sys; sys.stdout.write('.'.join([str(x) for x in sys.version_info[:3]]))"
- python3.7 -c "import sys; sys.stdout.write('.'.join([str(x) for x in sys.version_info[:3]]))"
- python3.6 -c "import sys; sys.stdout.write('.'.join([str(x) for x in sys.version_info[:3]]))"
- cmake --version
- cmake .
after_failure:
- cat CMakeCache.txt
env:
  global:
    - SEED=1
    - secure: "FrI5d2s+ckckC17T66c8jm2jV6i2DkBPU5nyWzwbedjmEBeocREfQLd/x8yKpPzLDz7ghOvr+/GQvsPPn0dVkGlNzm3Q+hGHc/ujnASuUtGrcuMM+0ALnJ3k4rFr9xEvjJeWb4SmhJO5UCAZYvTItW4k7+bj9L+R6lt3TzQbXzg="

addons:
  apt:
    packages:
    - doxygen
    - graphviz
